# User Configuration
# All driver Kconfig is in Kconfig.defconfig
CONFIG_ZMK_POINTING=y

# ディープスリープを有効にする
CONFIG_ZMK_SLEEP=y
# アイドル状態に移行するまでの時間（ミリ秒） デフォルト: 30000 (30秒)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# アイドル状態からディープスリープに移行するまでの時間（ミリ秒） デフォルト: 300000 (5分)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000